import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';

// Thuật toán LZW nguyên bản từ RWA_STATE (Giữ nguyên 100%)
const lzwCompress = (str) => {
  if (!str) return str;
  let dict = new Map(), out = [], phrase = str[0], code = 256;
  for (let i = 1; i < str.length; i++) {
    let curr = str[i];
    if (dict.has(phrase + curr)) phrase += curr;
    else {
      out.push(phrase.length > 1 ? dict.get(phrase) : phrase.charCodeAt(0));
      dict.set(phrase + curr, code++);
      phrase = curr;
      if (code > 60000) { dict.clear(); code = 256; }
    }
  }
  out.push(phrase.length > 1 ? dict.get(phrase) : phrase.charCodeAt(0));
  return out.map(c => String.fromCharCode(c)).join("");
};

const lzwDecompress = (str) => {
  if (!str) return str;
  let dict = new Map(), currChar = str[0], oldPhrase = currChar, out = [currChar], code = 256, phrase;
  for (let i = 1; i < str.length; i++) {
    let currCode = str.charCodeAt(i);
    if (currCode < 256) phrase = str[i];
    else phrase = dict.has(currCode) ? dict.get(currCode) : (oldPhrase + currChar);
    out.push(phrase);
    currChar = phrase.charAt(0);
    dict.set(code++, oldPhrase + currChar);
    oldPhrase = phrase;
    if (code > 60000) { dict.clear(); code = 256; }
  }
  return out.join("");
};

// VÁ LỖI TẠI ĐÂY: Nén toàn bộ Payload của Zustand để chống tràn LocalStorage
const customStorage = {
  getItem: (name) => {
    const value = localStorage.getItem(name);
    if (!value) return null;
    try {
      // Thử giải nén, nếu lỗi tức là data cũ dạng JSON thuần
      return lzwDecompress(value); 
    } catch (e) {
      return value; // Fallback an toàn
    }
  },
  setItem: (name, value) => {
    try {
      // Nén toàn bộ cục state (profiles, config, history) trước khi lưu
      const compressed = lzwCompress(value);
      localStorage.setItem(name, compressed);
    } catch (e) {
      localStorage.setItem(name, value); // Fallback an toàn
    }
  },
  removeItem: (name) => localStorage.removeItem(name),
};

const DEFAULT_PROFILES = [
  { id: "expand",      name: "Expand",               order: 0,  prompt: "Expand the selected text with more descriptive detail, sensory imagery, and depth while preserving the core meaning and narrative facts." },
  { id: "compress",    name: "Compress",              order: 1,  prompt: "Compress the selected text to be more concise while preserving all key information and narrative facts." },
  { id: "thoughts",    name: "Add Inner Thoughts",    order: 2,  prompt: "Add the POV character's inner thoughts and emotional reactions to the selected text, woven naturally into the prose." },
  { id: "dialogue",    name: "Convert to Dialogue",   order: 3,  prompt: "Convert the selected text into dialogue between characters, preserving the narrative information through spoken words and natural conversation." },
  { id: "active",      name: "Passive to Active",     order: 4,  prompt: "Rewrite the selected text converting passive voice constructions to active voice." },
  { id: "diffwords",   name: "Use Different Words",   order: 5,  prompt: "Rewrite the selected text using different vocabulary and phrasing while preserving the exact meaning and tone." },
  { id: "showdont",    name: "Show, Don't Tell",      order: 6,  prompt: "Rewrite the selected text to show through action, sensory detail, and dialogue rather than telling. Replace statements about emotions or states with concrete scenes that let the reader experience them." },
  { id: "emotion",     name: "Show More Emotion",     order: 7,  prompt: "Rewrite the selected text with heightened emotional depth, making the characters' feelings more vivid and present." },
  { id: "transitions", name: "Fix Transitions",       order: 8,  prompt: "Improve the flow and transitions in the selected text so ideas connect more smoothly and the prose reads naturally." },
  { id: "noai",        name: "Remove LLM-isms",       order: 9,  prompt: "Identify and remove common language patterns that reveal the text was generated by a language model, such as hollow affirmations, overused em-dashes, and formulaic sentence structures. Make it sound naturally human." },
  { id: "expdialogue", name: "Expand Dialogue",       order: 10, prompt: "Expand the dialogue in the selected text with more back-and-forth exchange, subtext, and distinct character voice." },
  { id: "romance",     name: "Increase Romance",      order: 11, prompt: "Rewrite the selected text with increased romantic tension, chemistry, and emotional intimacy between the characters." },
  { id: "grammar",     name: "Grammar Fix",           order: 12, prompt: "Correct all grammar, spelling, and punctuation errors in the selected text. Do not change the style or content." }
];

const DEFAULT_CONFIG = {
  cols: 3, rows: 3, typewriter: true, showDiff: true, lengthEnabled: false, lengthPct: 0, autoApply: false, popupPos: "auto", historyDepth: 5, compact: false, ollamaUrl: "", ollamaModel: "", injectChar: true, injectUser: true, freeMode: false, contextDepth: 4, onlyAltR: false
};

export const usePersistentStore = create(
  persist(
    (set, get) => ({
      profiles: DEFAULT_PROFILES,
      config: DEFAULT_CONFIG,
      customs: [],
      history: {},

      updateConfig: (newConfig) => set((state) => ({ config: { ...state.config, ...newConfig } })),
      updateProfiles: (profiles) => set({ profiles }),
      updateCustoms: (customs) => set({ customs }),
      
      pushHistory: (mid, text, start, end) => set((state) => {
        if (!mid) return state;
        const currentHist = state.history[mid] || { undo: [], redo: [] };
        
        const stateObj = { text, start, end };
        const lastUndo = currentHist.undo[0];
        const lastUndoText = lastUndo && typeof lastUndo === 'object' ? lastUndo.text : lastUndo;
        
        if (currentHist.undo.length > 0 && lastUndoText === text) return state;

        const newUndo = [stateObj, ...currentHist.undo];
        const depth = Math.max(1, Math.min(50, state.config.historyDepth || 20));
        if (newUndo.length > depth) newUndo.length = depth;

        return {
          history: {
            ...state.history,
            [mid]: { undo: newUndo, redo: [] }
          }
        };
      }),

      setHistoryData: (mid, undo, redo) => set((state) => ({
        history: { ...state.history, [mid]: { undo, redo } }
      })),

      clearAllData: () => set({
        profiles: DEFAULT_PROFILES,
        config: DEFAULT_CONFIG,
        customs: [],
        history: {}
      })
    }),
    {
      name: 'rwa-premium-storage', 
      storage: createJSONStorage(() => customStorage),
    }
  )
);