import { create } from 'zustand';
import { createJSONStorage, persist } from 'zustand/middleware';
import { useRuntimeStore } from './useRuntimeStore';

const HOST_STORAGE_KEY = 'rewrite-assistant-state-v2';
const LEGACY_LOCAL_STORAGE_KEY = 'rwa-premium-storage';
const STORE_VERSION = 2;
const MAX_PROFILES = 64;
const MAX_PROFILE_NAME = 80;
const MAX_PROMPT_CHARS = 5_000;
const MAX_CUSTOMS = 32;

const DEFAULT_PROFILES = [
  { id: 'expand', name: 'Expand', order: 0, prompt: 'Expand the selected text with more descriptive detail, sensory imagery, and depth while preserving the core meaning and narrative facts.' },
  { id: 'compress', name: 'Compress', order: 1, prompt: 'Compress the selected text to be more concise while preserving all key information and narrative facts.' },
  { id: 'thoughts', name: 'Add Inner Thoughts', order: 2, prompt: "Add the POV character's inner thoughts and emotional reactions to the selected text, woven naturally into the prose." },
  { id: 'dialogue', name: 'Convert to Dialogue', order: 3, prompt: 'Convert the selected text into dialogue between characters, preserving the narrative information through spoken words and natural conversation.' },
  { id: 'active', name: 'Passive to Active', order: 4, prompt: 'Rewrite the selected text converting passive voice constructions to active voice.' },
  { id: 'diffwords', name: 'Use Different Words', order: 5, prompt: 'Rewrite the selected text using different vocabulary and phrasing while preserving the exact meaning and tone.' },
  { id: 'showdont', name: "Show, Don't Tell", order: 6, prompt: 'Rewrite the selected text to show through action, sensory detail, and dialogue rather than telling. Replace statements about emotions or states with concrete scenes that let the reader experience them.' },
  { id: 'emotion', name: 'Show More Emotion', order: 7, prompt: "Rewrite the selected text with heightened emotional depth, making the characters' feelings more vivid and present." },
  { id: 'transitions', name: 'Fix Transitions', order: 8, prompt: 'Improve the flow and transitions in the selected text so ideas connect more smoothly and the prose reads naturally.' },
  { id: 'noai', name: 'Remove LLM-isms', order: 9, prompt: 'Identify and remove common language patterns that reveal the text was generated by a language model, such as hollow affirmations, overused em-dashes, and formulaic sentence structures. Make it sound naturally human.' },
  { id: 'expdialogue', name: 'Expand Dialogue', order: 10, prompt: 'Expand the dialogue in the selected text with more back-and-forth exchange, subtext, and distinct character voice.' },
  { id: 'romance', name: 'Increase Romance', order: 11, prompt: 'Rewrite the selected text with increased romantic tension, chemistry, and emotional intimacy between the characters.' },
  { id: 'grammar', name: 'Grammar Fix', order: 12, prompt: 'Correct all grammar, spelling, and punctuation errors in the selected text. Do not change the style or content.' },
];

const DEFAULT_CONFIG = {
  cols: 3,
  rows: 3,
  typewriter: true,
  showDiff: true,
  lengthEnabled: false,
  lengthPct: 0,
  autoApply: false,
  popupPos: 'auto',
  historyDepth: 5,
  compact: false,
  ollamaUrl: '',
  ollamaModel: '',
  injectChar: true,
  injectUser: true,
  freeMode: false,
  contextDepth: 4,
  onlyAltR: false,
};

function clampInteger(value, min, max, fallback) {
  const numeric = Number.parseInt(value, 10);
  return Number.isFinite(numeric) ? Math.max(min, Math.min(max, numeric)) : fallback;
}

function safeString(value, maxLength, fallback = '') {
  return typeof value === 'string' ? value.slice(0, maxLength) : fallback;
}

function sanitizeProfile(profile, index) {
  if (!profile || typeof profile !== 'object') return null;
  const name = safeString(profile.name, MAX_PROFILE_NAME).trim();
  const prompt = safeString(profile.prompt, MAX_PROMPT_CHARS).trim();
  if (!name || !prompt) return null;

  const color = typeof profile.color === 'string' && /^#[0-9a-f]{6}$/i.test(profile.color)
    ? profile.color
    : null;
  return {
    id: safeString(profile.id, 100, `profile-${index}`) || `profile-${index}`,
    name,
    prompt,
    order: Number.isFinite(Number(profile.order)) ? Number(profile.order) : index,
    color,
  };
}

function sanitizeProfiles(value) {
  if (!Array.isArray(value)) return DEFAULT_PROFILES.map((profile) => ({ ...profile }));
  return value.slice(0, MAX_PROFILES).map(sanitizeProfile).filter(Boolean);
}

function sanitizeCustoms(value) {
  if (!Array.isArray(value)) return [];
  return value
    .filter((item) => typeof item === 'string')
    .map((item) => item.slice(0, MAX_PROMPT_CHARS).trim())
    .filter(Boolean)
    .slice(0, MAX_CUSTOMS);
}

function sanitizeConfig(value) {
  const source = value && typeof value === 'object' ? value : {};
  return {
    cols: clampInteger(source.cols, 1, 6, DEFAULT_CONFIG.cols),
    rows: clampInteger(source.rows, 1, 10, DEFAULT_CONFIG.rows),
    typewriter: typeof source.typewriter === 'boolean' ? source.typewriter : DEFAULT_CONFIG.typewriter,
    showDiff: typeof source.showDiff === 'boolean' ? source.showDiff : DEFAULT_CONFIG.showDiff,
    lengthEnabled: typeof source.lengthEnabled === 'boolean' ? source.lengthEnabled : DEFAULT_CONFIG.lengthEnabled,
    lengthPct: clampInteger(source.lengthPct, -100, 300, DEFAULT_CONFIG.lengthPct),
    autoApply: typeof source.autoApply === 'boolean' ? source.autoApply : DEFAULT_CONFIG.autoApply,
    popupPos: ['auto', 'above', 'below'].includes(source.popupPos) ? source.popupPos : DEFAULT_CONFIG.popupPos,
    historyDepth: clampInteger(source.historyDepth, 1, 50, DEFAULT_CONFIG.historyDepth),
    compact: typeof source.compact === 'boolean' ? source.compact : DEFAULT_CONFIG.compact,
    ollamaUrl: safeString(source.ollamaUrl, 2_048),
    ollamaModel: safeString(source.ollamaModel, 256),
    injectChar: typeof source.injectChar === 'boolean' ? source.injectChar : DEFAULT_CONFIG.injectChar,
    injectUser: typeof source.injectUser === 'boolean' ? source.injectUser : DEFAULT_CONFIG.injectUser,
    freeMode: typeof source.freeMode === 'boolean' ? source.freeMode : DEFAULT_CONFIG.freeMode,
    contextDepth: clampInteger(source.contextDepth, 0, 20, DEFAULT_CONFIG.contextDepth),
    onlyAltR: typeof source.onlyAltR === 'boolean' ? source.onlyAltR : DEFAULT_CONFIG.onlyAltR,
  };
}

function lzwDecompress(value) {
  if (!value) return value;
  const dict = new Map();
  let currChar = value[0];
  let oldPhrase = currChar;
  const out = [currChar];
  let code = 256;

  for (let i = 1; i < value.length; i += 1) {
    const currCode = value.charCodeAt(i);
    const phrase = currCode < 256
      ? value[i]
      : (dict.has(currCode) ? dict.get(currCode) : oldPhrase + currChar);
    out.push(phrase);
    currChar = phrase.charAt(0);
    dict.set(code, oldPhrase + currChar);
    code += 1;
    oldPhrase = phrase;
    if (code > 60_000) {
      dict.clear();
      code = 256;
    }
  }
  return out.join('');
}

function readLegacyState() {
  const value = localStorage.getItem(LEGACY_LOCAL_STORAGE_KEY);
  if (!value) return null;

  const candidates = [value];
  try { candidates.unshift(lzwDecompress(value)); } catch { /* legacy value may already be plain JSON */ }
  for (const candidate of candidates) {
    try {
      JSON.parse(candidate);
      return candidate;
    } catch {
      // Try the next legacy representation.
    }
  }
  return null;
}

function getMarinaraStorage() {
  const marinara = useRuntimeStore.getState().marinara;
  return marinara?.storage && typeof marinara.storage.get === 'function' ? marinara.storage : null;
}

const hostStateStorage = {
  async getItem(name) {
    const storage = getMarinaraStorage();
    if (storage) {
      const values = await storage.get();
      const persisted = values?.[name];
      if (typeof persisted === 'string') return persisted;

      const legacy = readLegacyState();
      if (legacy) {
        await storage.patch({ [name]: legacy });
        localStorage.removeItem(LEGACY_LOCAL_STORAGE_KEY);
        return legacy;
      }
      return null;
    }

    return localStorage.getItem(name) ?? readLegacyState();
  },

  async setItem(name, value) {
    const storage = getMarinaraStorage();
    if (storage) {
      await storage.patch({ [name]: value });
      return;
    }
    localStorage.setItem(name, value);
  },

  async removeItem(name) {
    const storage = getMarinaraStorage();
    if (storage && typeof storage.clear === 'function') {
      await storage.clear();
    } else {
      localStorage.removeItem(name);
    }
    localStorage.removeItem(LEGACY_LOCAL_STORAGE_KEY);
  },
};

const defaultState = () => ({
  profiles: DEFAULT_PROFILES.map((profile) => ({ ...profile })),
  config: { ...DEFAULT_CONFIG },
  customs: [],
  history: {},
});

export const usePersistentStore = create(
  persist(
    (set, get) => ({
      ...defaultState(),

      updateConfig: (newConfig) => set((state) => ({
        config: sanitizeConfig({ ...state.config, ...newConfig }),
      })),
      updateProfiles: (profiles) => set({ profiles: sanitizeProfiles(profiles) }),
      updateCustoms: (customs) => set({ customs: sanitizeCustoms(customs) }),

      pushHistory: (mid, text, start, end) => set((state) => {
        if (!mid || typeof text !== 'string') return state;
        const currentHist = state.history[mid] || { undo: [], redo: [] };
        const stateObj = { text, start, end };
        const lastUndo = currentHist.undo[0];
        const lastUndoText = lastUndo && typeof lastUndo === 'object' ? lastUndo.text : lastUndo;
        if (currentHist.undo.length > 0 && lastUndoText === text) return state;

        const newUndo = [stateObj, ...currentHist.undo];
        const depth = Math.max(1, Math.min(50, state.config.historyDepth || 20));
        if (newUndo.length > depth) newUndo.length = depth;
        return {
          history: {
            ...state.history,
            [mid]: { undo: newUndo, redo: [] },
          },
        };
      }),

      setHistoryData: (mid, undo, redo) => set((state) => ({
        history: { ...state.history, [mid]: { undo, redo } },
      })),

      clearAllData: async () => {
        await hostStateStorage.removeItem(HOST_STORAGE_KEY);
        set(defaultState());
      },

      clearHistory: () => set({ history: {} }),
      getPersistentSnapshot: () => {
        const state = get();
        return {
          profiles: sanitizeProfiles(state.profiles),
          config: sanitizeConfig(state.config),
          customs: sanitizeCustoms(state.customs),
        };
      },
    }),
    {
      name: HOST_STORAGE_KEY,
      version: STORE_VERSION,
      storage: createJSONStorage(() => hostStateStorage),
      skipHydration: true,
      partialize: (state) => ({
        profiles: sanitizeProfiles(state.profiles),
        config: sanitizeConfig(state.config),
        customs: sanitizeCustoms(state.customs),
      }),
      merge: (persistedState, currentState) => {
        const persisted = persistedState && typeof persistedState === 'object' ? persistedState : {};
        return {
          ...currentState,
          profiles: sanitizeProfiles(persisted.profiles),
          config: sanitizeConfig(persisted.config),
          customs: sanitizeCustoms(persisted.customs),
          history: {},
        };
      },
    },
  ),
);
