import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const read = (path) => readFileSync(path, 'utf8');

const modal = read('./src/components/modals/SettingsModal.jsx');
const css = read('./src/styles-settings.js');
const main = read('./src/main.jsx');
const ui = read('./src/components/modals/settings/TabUI.jsx');
const context = read('./src/components/modals/settings/TabContext.jsx');
const data = read('./src/components/modals/settings/TabData.jsx');
const profiles = read('./src/components/modals/settings/TabProfiles.jsx');
const language = read('./src/components/modals/settings/TabLanguage.jsx');
const api = read('./src/components/modals/settings/TabAPI.jsx');
const schema = read('./src/store/persistence/schema.js');
const popupContext = read('./src/components/popup/ContextPanel.jsx');
const about = read('./src/components/modals/settings/AboutPanel.jsx');
const worldclass = read('./src/styles-worldclass.js');

assert.match(modal, /className="rwa-win rwas-settings"/);
assert.match(modal, /rwas-shell/);
assert.match(modal, /rwas-sidebar/);
assert.match(modal, /rwas-workspace/);
assert.match(modal, /scrollPositionsRef/);
assert.match(modal, /Changes save automatically/);
assert.match(modal, /Thay đổi được lưu tự động/);
assert.match(modal, /'Xong' : 'Done'/);
assert.doesNotMatch(modal, />Cancel<\/Button>/);
assert.doesNotMatch(modal, />OK<\/Button>/);
assert.match(modal, /rwas-page-actions/);
assert.match(modal, /\+ Add Style/);
assert.match(modal, /\+ Thêm thiết lập/);
assert.match(modal, /AI Architect/);
assert.doesNotMatch(modal, /useGlowPointer/);

assert.match(modal, /role="tablist"/);
assert.match(modal, /onKeyDown=\{handleNavKeyDown\}/);
assert.match(modal, /NAV_KEYS/);
assert.match(modal, /ArrowDown/);
assert.match(modal, /ArrowUp/);
assert.match(modal, /ArrowRight/);
assert.match(modal, /ArrowLeft/);
assert.match(modal, /event\.key === 'Home'/);
assert.match(modal, /event\.key === 'End'/);
assert.match(modal, /tabIndex=\{selected \? 0 : -1\}/);
assert.match(modal, /tabIndex=\{showAbout \? 0 : -1\}/);
assert.match(modal, /aria-controls="rwas-settings-panel"/);
assert.match(modal, /id="rwas-settings-panel"/);
assert.match(modal, /role="tabpanel"/);
assert.match(modal, /aria-labelledby=\{activeTabId\}/);
assert.match(modal, /<AboutPanel vi=\{vi\} \/>/);
assert.match(about, /Có gì mới từ bản React đầu tiên/);
assert.match(about, /21\/06\/2026/);
assert.match(about, /GHI CÔNG/);
assert.match(about, /Một người bạn đặc biệt/);
assert.match(about, /Beoopo — Marinara Rewrite/);
assert.ok(about.indexOf('Có gì mới từ bản React đầu tiên') < about.indexOf('GHI CÔNG'));
assert.match(worldclass, /\.rwa-about-feature-grid/);
assert.match(worldclass, /\.rwa-about-credit-list/);

assert.match(modal, /id: 'language'/);
assert.match(modal, /label: 'Language'/);
assert.match(modal, /labelVi: 'Ngôn ngữ'/);
assert.match(modal, /<TabLanguage \/>/);
assert.match(language, /value: 'vi'/);
assert.match(language, /name: 'Tiếng Việt'/);
assert.match(language, /value: 'en'/);
assert.match(language, /name: 'English'/);
assert.match(language, /updateConfig\(\{ uiLanguage: option\.value \}\)/);
assert.match(schema, /uiLanguage:\s*'en'/);
assert.match(schema, /\['en', 'vi'\]\.includes\(input\.uiLanguage\)/);

assert.match(css, /width:\s*min\(960px/);
assert.match(css, /height:\s*min\(720px/);
assert.match(css, /grid-template-columns:\s*224px minmax\(0, 1fr\)/);
assert.match(css, /\.rwas-nav\s*\{[\s\S]*flex:\s*1 1 auto/);
assert.match(css, /\.rwas-statusbar/);
assert.match(css, /backdrop-filter:\s*none/);
assert.match(css, /:focus-visible/);
assert.match(css, /prefers-reduced-motion/);
assert.doesNotMatch(css, /transition:\s*all/);
assert.match(css, /\.rwas-settings\s*\{[\s\S]*font-family:\s*var\(--rwa-host-font/);
assert.match(main, /getComputedStyle\?\.\(document\.body\)\?\.fontFamily/);
assert.match(main, /setProperty\('--rwa-host-font', marinaraFont\)/);
assert.match(css, /\.rwas-window-title\s*\{[\s\S]*font-size:\s*17px;[\s\S]*font-weight:\s*730;[\s\S]*letter-spacing:\s*-\.012em/);
assert.match(css, /\.rwas-nav-copy strong\s*\{[\s\S]*font-size:\s*12\.5px;[\s\S]*font-weight:\s*690/);
assert.match(css, /\.rwas-nav-copy small\s*\{[\s\S]*font-size:\s*11px/);
assert.match(css, /\.rwas-page-title\s*\{[\s\S]*font-size:\s*20px;[\s\S]*font-weight:\s*740/);
assert.match(css, /\.rwas-page-description\s*\{[\s\S]*font-size:\s*12px/);
assert.match(css, /\.rwas-body \.rwa-prev\s*\{\s*font-size:\s*11\.5px !important;\s*\}/);
assert.match(css, /\.rwas-body \.rwa-setting-toggle-row small\s*\{\s*font-size:\s*11px;\s*\}/);
assert.match(css, /\.rwas-body \.rwa-connection-note\s*\{\s*font-size:\s*11\.5px;\s*\}/);

assert.match(main, /import \{ RWA_SETTINGS_CSS \} from '\.\/styles-settings\.js';/);
assert.match(main, /RWA_PERFORMANCE_CSS\}\\n\$\{RWA_POPUP_CSS\}\\n\$\{RWA_SETTINGS_CSS\}/);
assert.doesNotMatch(css, /\.rwa2-/);

assert.doesNotMatch(ui, /Surrounding context words \/ side/);
assert.doesNotMatch(ui, /Clean Data|Reset Rewrite Assistant data/);
assert.match(ui, /Behavior & Viewports/);
assert.match(ui, /Giao diện & hiển thị/);
assert.match(ui, /Persona Reply launcher/);
assert.match(ui, /Nút Trả lời theo Persona/);
assert.match(ui, /draftReplyLauncherPlacement/);
assert.match(ui, /Auto — follow composer/);
assert.match(ui, /Tự động — theo ô nhập/);
assert.match(ui, /Remember dragged position/);
assert.match(ui, /Ghi nhớ vị trí kéo/);
assert.match(ui, /draftReplyLauncherPositions/);
assert.match(ui, /Reset position/);
assert.match(ui, /Đặt lại/);
assert.match(ui, /updateConfig\(\{ draftReplyLauncherPositions: \{\} \}\)/);
assert.match(context, /Surrounding context words \/ side/);
assert.match(context, /Số từ ngữ cảnh gần \/ mỗi phía/);
assert.match(context, /localContextWords/);
assert.match(context, /aria-label=\{text\('Surrounding context words per side', 'Số từ ngữ cảnh xung quanh mỗi phía'\)\}/);
assert.match(data, /DATA RESET/);
assert.match(data, /ĐẶT LẠI DỮ LIỆU/);
assert.match(data, /Reset Rewrite Assistant data/);
assert.match(data, /usePersistentStore\.persist\.clearStorage/);
assert.match(data, /STORAGE_KEY/);
assert.match(data, /LEGACY_BACKUP_KEY/);
assert.match(profiles, /Search profiles/);
assert.match(profiles, /Tìm thiết lập/);
assert.doesNotMatch(`${context}\n${data}`, /rwa-glow-button/);

assert.match(api, /Diagnose LAN access/);
assert.match(api, /Chẩn đoán kết nối LAN/);
assert.match(api, /OLLAMA_HOST=0\.0\.0\.0:11434/);
assert.match(api, /OLLAMA_ORIGINS=\$\{browserOrigin\}/);
assert.match(api, /Local Network/);
assert.match(api, /NGUỒN MODEL/);
assert.match(api, /Fast rewrite/);
assert.match(api, /Viết lại nhanh/);
assert.match(api, /Follow current chat \(default\)/);
assert.match(api, /Use a specific Marinara connection/);
assert.match(api, /Normal Marinara rewrites do not use a client-side deadline/);
assert.match(popupContext, /Fast Rewrite/);
assert.match(popupContext, /Viết lại nhanh/);
assert.match(popupContext, /FAST_REWRITE_HELP/);
assert.match(popupContext, /updateConfig\(\{ fastRewrite: value \}\)/);
assert.match(schema, /cols:\s*4/);
assert.match(schema, /rows:\s*4/);
assert.match(schema, /historyDepth:\s*1/);
assert.match(schema, /contextDepth:\s*1/);
assert.match(schema, /fastRewrite:\s*true/);
assert.match(schema, /fastRewrite:\s*cleanBoolean/);
assert.match(schema, /marinaraRouting:\s*'chat'/);
assert.match(schema, /draftReplyLauncherPlacement:\s*'auto'/);
assert.match(schema, /draftReplyLauncherPositions:\s*\{\}/);
assert.match(schema, /sanitizeDraftReplyLauncherPositions/);
assert.match(schema, /\['auto', 'remember'\]\.includes\(input\.draftReplyLauncherPlacement\)/);
assert.match(schema, /DRAFT_REPLY_CHAT_MODES\s*=\s*\['roleplay', 'conversation', 'game'\]/);

console.log('settingscheck: isolated bilingual settings shell/semantics/information-architecture contract passed');

assert.doesNotMatch(modal, /labelVi: 'Kiểu viết'/);
assert.doesNotMatch(profiles, /Tìm style/);
